name: Nightly Deployment

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  nightly-build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Source Repo
      uses: actions/checkout@v3
      with:
        repository: erudman21/reactjs-go-mysql-sample-app
        path: source
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Create temp EC2
      run: true
    
    - name: Run smoke tests
      run: true
    
    - name: Build and push Docker images
      run: true
    
    - name: Deploy to QA
      run: true